#!/usr/bin/with-contenv bash

groupmod -o -g "${PUID:-911}" abc >/dev/null 2>&1
usermod -o -u "${PGID:-911}" abc >/dev/null 2>&1

if [ "$(date +%Y)" == "1970" ] && [ "$(uname -m)" == "armv7l" ]; then
	echo '
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

Your DockerHost is most likely running an outdated version of libseccomp

To fix this, please visit https://docs.linuxserver.io/faq#libseccomp

Some apps might not behave correctly without this

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
'
fi

echo "
-------------------------------------
.._..............._
.|.|.............|.|
.|.|__.._..._..__|.|.__._.____
.|.'_.\|.|.|.|/._\`.|/._\`.|_../
.|.|.|.|.|_|.|.(_|.|.(_|.|/./
.|_|.|_|\__,.|\__,_|\__,_/___|
.........__/.|
........|___/
-------------------------------------"
if [[ -f /donate.txt ]]; then
	echo "
To support the app dev(s) visit:
$(cat /donate.txt)
-------------------------------------"
fi
echo "
GID/UID
-------------------------------------
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------"

chown abc:abc \
	/app \
	/config \
	/defaults
