#!/usr/bin/with-contenv bash

usermod -o -u "${PUID:-911}" abc &>/dev/null
groupmod -o -g "${PGID:-911}" abc &>/dev/null

echo "
-------------------------------------
.._..............._
.|.|.............|.|
.|.|__.._..._..__|.|.__._.____
.|.'_.\|.|.|.|/._\`.|/._\`.|_../
.|.|.|.|.|_|.|.(_|.|.(_|.|/./
.|_|.|_|\__,.|\__,_|\__,_/___|
.........__/.|
........|___/
-------------------------------------"
if [[ -f /donate.txt ]]; then
	echo "
To support the app dev(s) visit:
$(cat /donate.txt)
-------------------------------------"
fi
echo "
GID/UID
-------------------------------------
User UID:    $(id -u abc)
User GID:    $(id -g abc)
-------------------------------------"

chown abc:abc \
	/app \
	/config \
	/defaults
